/**
 * MATH-CS COMPASS: Algebraic Map (Visibility Enhanced)
 */
const renderAlgebraCompass = () => {
    const root = document.getElementById('algebra-map-root');
    if (!root) return;

    const structures = [
        { name: "Group",                        r: 280, color: "#2d3436", desc: "A set with an associative operation and inverses. The foundation of symmetry.", ex: "Symmetric Group Sₙ, (ℤ, +)" },
        { name: "Ring",                         r: 235, color: "#34495e", desc: "Adds a second operation (multiplication). Essential for matrix and polynomial algebra.", ex: "Matrix Ring Mₙ(ℝ), ℤ[x]" },
        { name: "Integral Domain",              r: 190, color: "#2980b9", desc: "A commutative ring with no zero divisors. Ensures ab=0 implies a=0 or b=0.", ex: "ℤ[√-5] (Not a UFD!)" },
        { name: "Unique Factorization Domain",  r: 145, color: "#8e44ad", desc: "Every non-zero non-unit can be written uniquely as a product of irreducibles.", ex: "ℤ[x] (A UFD, but not a PID)" },
        { name: "Principal Ideal Domain",       r: 105, color: "#5f27cd", desc: "An integral domain where every ideal is generated by a single element.", ex: "The Integers ℤ, ℚ[x]" },
        { name: "Euclidean Domain",             r: 70,  color: "#341f97", desc: "A domain where division with remainder exists, enabling the Euclidean Algorithm.", ex: "ℤ, ℤ[i]" },
        { name: "Field",                        r: 35,  color: "#00d2d3", desc: "The strongest structure. Every non-zero element has a multiplicative inverse.", ex: "ℚ, ℝ, ℂ, GF(2ⁿ)" }
    ];

    root.innerHTML = `
        <style>
            .map-layer { cursor: pointer; transition: all 0.3s ease; stroke: rgba(255,255,255,0.1); stroke-width: 1; fill-opacity: 0.75; }
            .map-layer:hover { fill-opacity: 1; stroke: #00d2d3; stroke-width: 3; filter: drop-shadow(0 0 12px rgba(0,210,211,0.6)); }
            .compass-label { font-family: 'Inter', sans-serif; font-size: 13px; fill: #ecf0f1; font-weight: bold; pointer-events: none; text-transform: uppercase; letter-spacing: 1px; opacity: 0.6; }
            .main-label { opacity: 1; font-size: 15px; fill: #00d2d3; }
            .compass-center-label { font-family: 'Inter', sans-serif; font-size: 10px; fill: #fff; font-weight: bold; text-anchor: middle; pointer-events: none; }
            #structure-info-box { 
                width: 100%; max-width: 600px; min-height: 160px; padding: 20px; 
                border-radius: 12px; background: #1e272e; border: 1px solid #34495e; 
                border-left: 5px solid #00d2d3; box-shadow: 0 10px 30px rgba(0,0,0,0.5); margin-top: 15px; 
            }
            #info-name { color: #00d2d3; margin: 0 0 8px 0; font-size: 1.5em; }
            #info-desc { color: #dcdde1; margin: 0 0 12px 0; font-size: 0.95em; line-height: 1.6; }
            #info-ex { color: #00d2d3; margin: 0; font-size: 0.9em; font-weight: bold; }
        </style>

        <svg id="algebra-svg" viewBox="0 0 600 600" style="max-width: 500px; width: 100%; height: auto;">
            ${structures.map(s => `
                <circle cx="300" cy="300" r="${s.r}" class="map-layer" fill="${s.color}" data-name="${s.name}"></circle>
            `).join('')}

            <text x="300" y="45" text-anchor="middle" class="compass-label main-label">Groups</text>
            <text x="300" y="85" text-anchor="middle" class="compass-label">Rings</text>
            <text x="300" y="130" text-anchor="middle" class="compass-label">Domains</text>
            <text x="300" y="175" text-anchor="middle" class="compass-label" style="font-size: 10px;">UFDs</text>
            <text x="300" y="215" text-anchor="middle" class="compass-label" style="font-size: 10px;">PIDs</text>
            <text x="300" y="245" text-anchor="middle" class="compass-label" style="font-size: 9px;">EDs</text>
            <text x="300" y="304" class="compass-center-label">FIELD</text>
        </svg>

        <div id="structure-info-box">
            <h3 id="info-name">Hierarchy of Integrity</h3>
            <p id="info-desc">Hover over the layers to explore how mathematical structures nest. The innermost Field represents the pinnacle of algebraic utility.</p>
            <p id="info-ex"></p>
        </div>
    `;

    const nameEl = document.getElementById('info-name');
    const descEl = document.getElementById('info-desc');
    const exEl = document.getElementById('info-ex');

    root.querySelectorAll('.map-layer').forEach(layer => {
        layer.addEventListener('mouseenter', () => {
            const name = layer.getAttribute('data-name');
            const data = structures.find(s => s.name === name);
            nameEl.textContent = data.name;
            descEl.textContent = data.desc;
            exEl.textContent = `Example: ${data.ex}`;
        });
    });
};

renderAlgebraCompass();