/**
 * MATH-CS COMPASS: Integrated Algebraic Map
 * Encapsulates UI, Data, and Logic for the hierarchy of algebraic structures.
 */
const renderAlgebraCompass = () => {
    const root = document.getElementById('algebra-map-root');
    if (!root) return;

    // 1. Data Definition
    const structures = [
        { name: "Group",            r: 280, color: "#d1d8e0", desc: "A set with one operation. Focuses on symmetry and inverses.", ex: "Symmetric Group Sₙ, (ℤ, +)" },
        { name: "Ring",             r: 235, color: "#a5b1c2", desc: "Two operations (add/mult). The foundation for matrix and polynomial math.", ex: "Matrix Ring Mₙ(ℝ), ℤ[x]" },
        { name: "Integral Domain",  r: 190, color: "#778ca3", desc: "Commutative rings with no zero divisors. Ensures data integrity.", ex: "ℤ[√-5] (Not a UFD!)" },
        { name: "UFD",              r: 145, color: "#4b6584", desc: "Unique Factorization Domain. Guaranteed unique 'prime' decomposition.", ex: "ℤ[x] (A UFD, but not a PID!)" },
        { name: "PID",              r: 105, color: "#3867d6", desc: "Every ideal is generated by a single 'key'. Irreducibles are always primes.", ex: "ℤ, ℚ[x]" },
        { name: "Euclidean Domain", r: 70,  color: "#2d98da", desc: "Division algorithm exists. Allows for the Euclidean Algorithm (RSA foundation).", ex: "ℤ, ℚ[x], ℤ[i]" },
        { name: "Field",            r: 35,  color: "#0fbcf9", desc: "The most rigid structure. Division by any non-zero element is possible.", ex: "ℚ, ℝ, ℂ, GF(2ⁿ)" }
    ];

    // 2. Generate UI Components
    root.innerHTML = `
        <style>
            .map-layer { cursor: pointer; transition: all 0.3s ease; stroke: #fff; stroke-width: 1; fill-opacity: 0.7; }
            .map-layer:hover { fill-opacity: 1; stroke: #2c3e50; stroke-width: 3; }
            .compass-label { font-family: 'Segoe UI', Tahoma, sans-serif; font-size: 14px; fill: #2c3e50; font-weight: bold; pointer-events: none; }
            .compass-center-label { font-family: 'Segoe UI', Tahoma, sans-serif; font-size: 12px; fill: #fff; font-weight: bold; text-anchor: middle; pointer-events: none; }
            #structure-info-box { width: 100%; max-width: 500px; min-height: 140px; padding: 20px; border-radius: 8px; background: #f9f9f9; border-left: 5px solid #2d98da; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }
        </style>

        <svg id="algebra-svg" viewBox="0 0 600 600" style="max-width: 500px; width: 100%; height: auto;">
            ${structures.map(s => `
                <circle cx="300" cy="300" r="${s.r}" class="map-layer" fill="${s.color}" data-name="${s.name}"></circle>
            `).join('')}
            <text x="300" y="45" text-anchor="middle" class="compass-label">Groups</text>
            <text x="300" y="305" class="compass-center-label">Field</text>
        </svg>

        <div id="structure-info-box">
            <h3 id="info-name" style="margin: 0 0 10px 0; color: #2c3e50;">Algebraic Hierarchy</h3>
            <p id="info-desc" style="margin: 0 0 10px 0; font-size: 0.95em; line-height: 1.5; color: #444;">Hover over the map layers to see how algebraic structures are nested.</p>
            <p id="info-ex" style="margin: 0; font-size: 0.85em; font-style: italic; color: #666;"></p>
        </div>
    `;

    // 3. Add Interactions
    const nameEl = document.getElementById('info-name');
    const descEl = document.getElementById('info-desc');
    const exEl = document.getElementById('info-ex');

    root.querySelectorAll('.map-layer').forEach(layer => {
        layer.addEventListener('mouseenter', () => {
            const name = layer.getAttribute('data-name');
            const data = structures.find(s => s.name === name);
            nameEl.textContent = data.name;
            descEl.textContent = data.desc;
            exEl.textContent = `Example: ${data.ex}`;
        });
    });
};

// Start the app when the DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderAlgebraCompass);
} else {
    renderAlgebraCompass();
}