/**
 * MATH-CS COMPASS: Algebraic Map
 */
const renderAlgebraCompass = () => {
    const root = document.getElementById('algebra-map-root');
    if (!root) return;

    const structures = [
        { name: "Group", r: 280, color: "#2d3436",
          desc: "A set with an associative operation and inverses. The foundation of symmetry.",
          ex: "Symmetric Groups Sₙ, Cyclic Groups Cₙ" },
        { name: "Ring", r: 235, color: "#34495e",
          desc: "Adds a second operation (multiplication). Essential for matrix and polynomial algebra.",
          ex: "Matrix Rings Mₙ(R), Polynomial Rings R[x]" },
        { name: "Integral Domain", r: 190, color: "#2980b9",
          desc: "A commutative ring with no zero divisors.",
          ex: "ℤ[√-5] (Not a UFD!)" },
        { name: "Unique Factorization Domain", r: 145, color: "#8e44ad",
          desc: "Every non-zero non-unit factors uniquely.",
          ex: "ℤ[x]" },
        { name: "Principal Ideal Domain", r: 105, color: "#5f27cd",
          desc: "Every ideal is generated by one element.",
          ex: "ℤ, F[x]" },
        { name: "Euclidean Domain", r: 70, color: "#341f97",
          desc: "Division with remainder exists.",
          ex: "ℤ, ℤ[i]" },
        { name: "Field", r: 35, color: "#00d2d3",
          desc: "Every non-zero element has an inverse.",
          ex: "ℚ, ℝ, GF(p)" }
    ];

    root.innerHTML = `
    <style>
        .map-layer { cursor:pointer; transition:all .25s ease;
        stroke:rgba(255,255,255,.15); stroke-width:1; fill-opacity:.75; }
        .map-layer.active { fill-opacity:1; stroke:#00d2d3; stroke-width:3;
        filter:drop-shadow(0 0 10px rgba(0,210,211,.5)); }
        .map-hit { pointer-events:stroke; }

        .compass-label{font-family:Inter,sans-serif;font-size:13px;fill:#ecf0f1;
        font-weight:bold;pointer-events:none;text-transform:uppercase;letter-spacing:1px;opacity:.6;}
        .main-label{opacity:1;font-size:15px;fill:#00d2d3;}
        .compass-center-label{font-family:Inter,sans-serif;font-size:10px;fill:#fff;
        font-weight:bold;text-anchor:middle;pointer-events:none;}

        #structure-info-box{width:100%;max-width:600px;min-height:160px;padding:20px;
        border-radius:12px;background:#1e272e;border:1px solid #34495e;
        border-left:5px solid #00d2d3;box-shadow:0 10px 30px rgba(0,0,0,.5);margin-top:15px;}
        #info-name{color:#00d2d3;margin:0 0 8px;font-size:1.5em;}
        #info-desc{color:#dcdde1;margin:0 0 12px;font-size:.95em;line-height:1.6;}
        #info-ex{color:#00d2d3;margin:0;font-size:.9em;font-weight:bold;}
    </style>

    <svg viewBox="0 0 600 600" style="max-width:500px;width:100%;height:auto;">

    ${structures.map((s,i)=>`
    <!-- display  -->
    <circle cx="300" cy="300" r="${s.r}"
        class="map-layer" fill="${s.color}" data-name="${s.name}"></circle>

    <!-- tap -->
    <circle cx="300" cy="300" r="${s.r}"
        fill="none" stroke="transparent"
        stroke-width="${s.r - (structures[i+1]?.r || 0)}"
        class="map-hit" data-name="${s.name}">
    </circle>
    `).join('')}

    <text x="300" y="45" text-anchor="middle" class="compass-label main-label">Groups</text>
    <text x="300" y="85" text-anchor="middle" class="compass-label">Rings</text>
    <text x="300" y="130" text-anchor="middle" class="compass-label">Domains</text>
    <text x="300" y="175" text-anchor="middle" class="compass-label" style="font-size:10px;">UFDs</text>
    <text x="300" y="215" text-anchor="middle" class="compass-label" style="font-size:10px;">PIDs</text>
    <text x="300" y="245" text-anchor="middle" class="compass-label" style="font-size:9px;">EDs</text>
    <text x="300" y="304" class="compass-center-label">FIELD</text>
    </svg>

    <div id="structure-info-box">
    <h3 id="info-name">Hierarchy of Integrity</h3>
    <p id="info-desc">Tap a layer to explore how structures nest.</p>
    <p id="info-ex"></p>
    </div>
    `;

    const nameEl = document.getElementById('info-name');
    const descEl = document.getElementById('info-desc');
    const exEl   = document.getElementById('info-ex');

    root.querySelectorAll('.map-hit').forEach(hit => {
        const activate = () => {
            const name = hit.dataset.name;
            const data = structures.find(s => s.name === name);

            nameEl.textContent = data.name;
            descEl.textContent = data.desc;
            exEl.textContent   = `Example: ${data.ex}`;

            root.querySelectorAll('.map-layer')
                .forEach(l => l.classList.remove('active'));
            root.querySelector(`.map-layer[data-name="${name}"]`)
                .classList.add('active');
        };

        hit.addEventListener('click', activate);
        if (!('ontouchstart' in window)) {
            hit.addEventListener('mouseenter', activate);
        }
    });
};

renderAlgebraCompass();
