#!/usr/bin/env node
/*
 * build_atlas.js — generate SITE_ATLAS.md from curriculum.json.
 *
 * Usage (from repo root, like build_previews.js):
 *   node build_atlas.js [path/to/curriculum.json] [output.md]
 *
 * Defaults: data/curriculum.json -> SITE_ATLAS.md
 *
 * NOTE: GROUP_TITLES must be kept in sync with map/atlas.html.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const GROUP_TITLES = {
  'la-core': 'Core Linear Algebra',
  'matrix-analysis': 'Matrix Analysis',
  'group-theory': 'Group Theory',
  'ring-and-field': 'Rings & Fields',
  'lie-theory': 'Lie Theory',
  'representation-theory': 'Representation Theory',
  'quantum': 'Quantum Computation',
  'lattice': 'Lattice Geometry',
  'derivatives': 'Derivatives',
  'optimization': 'Optimization',
  'integration-and-measure': 'Integration & Measure',
  'fourier': 'Fourier Analysis',
  'topology-and-metric': 'Topology & Metric Spaces',
  'functional-analysis': 'Functional Analysis',
  'manifold-foundations': 'Manifold Foundations',
  'submanifolds-and-maps': 'Submanifolds & Smooth Maps',
  'lie-groups-on-manifolds': 'Lie Groups on Manifolds',
  'vector-fields-and-flows': 'Vector Fields & Flows',
  'bundles-on-manifolds': 'Bundles',
  'tensors-on-manifolds': 'Tensors',
  'riemannian-geometry': 'Riemannian Geometry',
  'differential-forms': 'Differential Forms',
  'orientations': 'Orientations',
  'integration': 'Integration on Manifolds',
  'foundations': 'Foundations',
  'distributions': 'Distributions',
  'multivariate': 'Multivariate Analysis',
  'classical-inference': 'Classical Inference',
  'information': 'Information Theory',
  'measure-theoretic': 'Measure-Theoretic Probability',
  'bayesian': 'Bayesian Methods',
  'stochastic-processes': 'Stochastic Processes',
  'graph-theory': 'Graph Theory',
  'combinatorics': 'Combinatorics',
  'computation': 'Theory of Computation',
  'logic': 'Logic & Formal Methods',
  'algebraic-topology': 'Algebraic Topology',
  'category-theory': 'Category Theory',
  'cryptography': 'Cryptography',
  'ml-foundations': 'ML Foundations',
  'deep-learning': 'Deep Learning',
  'generative-models': 'Generative Models',
  'security': 'Security'
};

const SECTION_ORDER = ['I', 'II', 'III', 'IV', 'V'];

function groupTitle(slug) {
  if (GROUP_TITLES[slug]) return GROUP_TITLES[slug];
  if (!slug) return 'Other';
  return slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function pageNumber(id) {
  const m = /-(\d+)$/.exec(id || '');
  return m ? m[1] : '?';
}

function main() {
  const inPath = process.argv[2] || path.join('data', 'curriculum.json');
  const outPath = process.argv[3] || 'SITE_ATLAS.md';

  const data = JSON.parse(fs.readFileSync(inPath, 'utf8'));
  const lines = [];
  let total = 0;

  lines.push('# MATH-CS COMPASS — Site Atlas');
  lines.push('');
  lines.push(`> Auto-generated by \`build_atlas.js\` from \`${inPath}\``
    + ` (curriculum v${(data.meta && data.meta.version) || '?'},`
    + ` lastUpdated ${(data.meta && data.meta.lastUpdated) || '?'}).`
    + ' Do not edit manually.');
  lines.push('');

  for (const key of SECTION_ORDER) {
    const sec = data.sections && data.sections[key];
    if (!sec || !sec.parts || !sec.parts.length) continue;

    lines.push(`## ${key} — ${sec.title} (${sec.parts.length})`);
    lines.push('');

    // group in first-appearance (curriculum) order
    const order = [];
    const byGroup = {};
    for (const p of sec.parts) {
      const g = p.topicGroup || 'other';
      if (!byGroup[g]) { byGroup[g] = []; order.push(g); }
      byGroup[g].push(p);
    }

    for (const g of order) {
      lines.push(`### ${groupTitle(g)} (${byGroup[g].length})`);
      lines.push('');
      for (const p of byGroup[g]) {
        total += 1;
        const link = (sec.baseUrl || '') + (p.url || '');
        lines.push(`- ${pageNumber(p.id)}. ${p.title} — \`${p.id}\` — ${link}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`Total: ${total} pages.`);
  lines.push('');

  fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log(`SITE_ATLAS.md: ${total} pages -> ${outPath}`);
}

main();
